"""
Django settings for piakweb project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
# Security / Debug
# -------------------------
SECRET_KEY = 'django-insecure-9ncgj9^_n1@jf9#pwua$m*0jw-mchmz%-!)ppj8b388-#z(5bu'
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]  # โปรดใส่โดเมนจริงตอน production

# -------------------------
# Auth redirects (ของระบบ session ที่เปี๊ยกทำเองก็ได้)
# -------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/product_list/'
LOGOUT_REDIRECT_URL = '/login/'

# -------------------------
# Installed apps
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'piakweb.apps.PiakwebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'piakweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # ถ้ามีโฟลเดอร์ templates นอก app ค่อยใส่ BASE_DIR / "templates"
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'piakweb.wsgi.application'

# -------------------------
# Database (PostgreSQL schema)
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'suenonkin',
        'USER': 'suenonkin_user',
        'PASSWORD': '50910402',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=suenonkin,public'
        }
    }
}

# -------------------------
# Internationalization
# -------------------------
LANGUAGE_CODE = 'th'
TIME_ZONE = 'Asia/Bangkok'
USE_TZ = True

# -------------------------
# Static / Media
# -------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "piakweb" / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------
# Password reset settings
# -------------------------
PASSWORD_RESET_TIMEOUT = 60 * 60 * 2  # 2 ชั่วโมง
RESET_TOKEN_TTL_HOURS = 2

# -------------------------
# Email
# -------------------------
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "IPS AUTOPARTS <noreply@ipsautoparts.local>"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.yourprovider.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "noreply@yourdomain.com"
    EMAIL_HOST_PASSWORD = "YOUR_PASSWORD"
    DEFAULT_FROM_EMAIL = "IPS AUTOPARTS <noreply@yourdomain.com>"
