# Generated by Django 5.2.8 on 2025-12-30 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SAASUSER',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('trial_end_date', models.DateField()),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('grace_period_end', models.DateField()),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SUBSCRIPTION',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='payment_slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='piakweb.subscription')),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.BigAutoField(db_column='TENANT_ID', primary_key=True, serialize=False)),
                ('shop_name', models.CharField(db_column='SHOP_NAME', max_length=200)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='piakweb.saasuser')),
            ],
            options={
                'db_table': 'TENANT',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='piakweb.tenant'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(db_column='PRODUCT_ID', primary_key=True, serialize=False)),
                ('product_code', models.CharField(db_column='PRODUCT_CODE', max_length=50)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=200)),
                ('SalePrice', models.DecimalField(db_column='SALEPRICE', decimal_places=2, default=0, max_digits=10)),
                ('lastbyprice', models.DecimalField(db_column='LASTBYPRICE', decimal_places=2, default=0, max_digits=10)),
                ('saleprice1', models.DecimalField(db_column='SALEPRICE1', decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(db_column='STOCK', default=0)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('tenant', models.ForeignKey(db_column='TENANT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='piakweb.tenant')),
            ],
            options={
                'db_table': 'B_PRODUCT',
                'indexes': [models.Index(fields=['tenant', 'product_name'], name='IX_B_PRODUCT_TENANT_NAME')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product_code'), name='UQ_B_PRODUCT_TENANT_CODE')],
            },
        ),
    ]
