# Generated by Django 5.2.8 on 2026-01-02 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piakweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ar_id', models.BigAutoField(db_column='AR_ID', primary_key=True, serialize=False)),
                ('ar_code', models.CharField(db_column='AR_CODE', max_length=50)),
                ('ar_name', models.CharField(db_column='AR_NAME', max_length=200)),
                ('contact_name', models.CharField(blank=True, db_column='CONTACT_NAME', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254, null=True)),
                ('line_id', models.CharField(blank=True, db_column='LINE_ID', max_length=100, null=True)),
                ('address1', models.CharField(blank=True, db_column='ADDRESS1', max_length=255, null=True)),
                ('address2', models.CharField(blank=True, db_column='ADDRESS2', max_length=255, null=True)),
                ('subdistrict', models.CharField(blank=True, db_column='SUBDISTRICT', max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_column='DISTRICT', max_length=100, null=True)),
                ('province', models.CharField(blank=True, db_column='PROVINCE', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZIPCODE', max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, db_column='TAX_ID', max_length=30, null=True)),
                ('branch_no', models.CharField(blank=True, db_column='BRANCH_NO', max_length=10, null=True)),
                ('credit_days', models.IntegerField(db_column='CREDIT_DAYS', default=0)),
                ('credit_limit', models.DecimalField(db_column='CREDIT_LIMIT', decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('tenant', models.ForeignKey(db_column='TENANT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='piakweb.tenant')),
            ],
            options={
                'db_table': 'B_AR',
                'indexes': [models.Index(fields=['tenant', 'ar_name'], name='IX_B_AR_TENANT_NAME'), models.Index(fields=['tenant', 'phone'], name='IX_B_AR_TENANT_PHONE')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ar_code'), name='UQ_B_AR_TENANT_CODE')],
            },
        ),
    ]
