# Generated by Django 5.2.11 on 2026-02-04 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piakweb', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='SalePrice',
            field=models.DecimalField(db_column='saleprice', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='lastbyprice',
            field=models.DecimalField(db_column='lastbyprice', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='saleprice1',
            field=models.DecimalField(db_column='saleprice1', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
